#!/usr/bin/env python3
"""Build the New Relic API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {
    'Infrastructure Alerts': 'Infra Alerts',
    'Telemetry SDK': 'Telemetry SDK',
    'OpenTelemetry': 'OpenTelemetry',
    'NRQL Lookups': 'NRQL Lookups',
    'Security Data': 'Security Data',
}

LINES = [
    {
        "name": 'Core APIs',
        "color": '#008C99',
        "stations": [
        ('REST API v2', (270, 200)),
        ('NerdGraph', (440, 175)),
        ('Metric', (610, 165)),
        ('Event', (790, 175)),
        ('Log', (970, 200)),
        ],
    },
    {
        "name": 'Telemetry & Tracing',
        "color": '#1E5BD0',
        "stations": [
        ('Trace', (270, 320)),
        ('Telemetry SDK', (420, 295)),
        ('OpenTelemetry', (580, 295)),
        ('Mobile SDK', (740, 295)),
        ],
    },
    {
        "name": 'Alerts & Synthetics',
        "color": '#E68B1F',
        "stations": [
        ('Alerts', (270, 460)),
        ('Synthetics', (430, 435)),
        ('Infrastructure Alerts', (620, 435)),
        ('Browser', (820, 435)),
        ('NRQL Lookups', (980, 460)),
        ],
    },
    {
        "name": 'Platform',
        "color": '#5A6275',
        "closed": True,
        "stations": [
        ('Partnership', (820, 590)),
        ('Control', (910, 660)),
        ('Security Data', (730, 660)),
        ],
    },
]

URL_OVERRIDES = {
    'REST API v2': 'https://apis.apis.io/apis/new-relic/new-relic-rest-api-v2/',
    'NerdGraph': 'https://apis.apis.io/apis/new-relic/new-relic-nerdgraph-api/',
    'Metric': 'https://apis.apis.io/apis/new-relic/new-relic-metric-api/',
    'Event': 'https://apis.apis.io/apis/new-relic/new-relic-event-api/',
    'Log': 'https://apis.apis.io/apis/new-relic/new-relic-log-api/',
    'Trace': 'https://apis.apis.io/apis/new-relic/new-relic-trace-api/',
    'Telemetry SDK': 'https://apis.apis.io/apis/new-relic/new-relic-telemetry-sdk/',
    'OpenTelemetry': 'https://apis.apis.io/apis/new-relic/new-relic-opentelemetry-otlp/',
    'Mobile SDK': 'https://apis.apis.io/apis/new-relic/new-relic-mobile-sdk/',
    'Alerts': 'https://apis.apis.io/apis/new-relic/new-relic-alerts-api/',
    'Synthetics': 'https://apis.apis.io/apis/new-relic/new-relic-synthetics-api/',
    'Infrastructure Alerts': 'https://apis.apis.io/apis/new-relic/new-relic-infrastructure-alerts-api/',
    'Browser': 'https://apis.apis.io/apis/new-relic/new-relic-browser-api/',
    'NRQL Lookups': 'https://apis.apis.io/apis/new-relic/new-relic-nrql-lookups-api/',
    'Partnership': 'https://apis.apis.io/apis/new-relic/new-relic-partnership-api/',
    'Control': 'https://apis.apis.io/apis/new-relic/new-relic-control/',
    'Security Data': 'https://apis.apis.io/apis/new-relic/new-relic-security-data-api/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The New Relic API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: new-relic/openapi · github.com/api-evangelist/new-relic',
        out_dir=Path(__file__).resolve().parent,
        out_basename='new-relic-subway-map',
        provider_id='new-relic',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
